export { default as filteredQuery } from './filteredQuery.js';
export { default as getObjFromParams } from './getSearchParamsValues.js';
export { default as resetDate } from './resetDate.js';
export { default as isSpiderName } from './spirerMan-normalizer.js';
export { default as findTitle } from './findTitle.js'
export { default as isEnglish } from './isEnglish.js'
export { default as getImage } from './imageConverter.js';
export { default as urlNormalizer } from './urlNormalizer.js';
export { default as pageToTop } from './pageToTop.js';